[project]
name = "speechtomath"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "openai-whisper",      # Whisper + Torch
    "sympy>=1.14",
    "lark",
    "openai",
    "matplotlib",
]